b2b/Controllers/CommonFunctionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using B2B.Models.Entity;
using B2B.Dto;
using System.Web.Mvc;

namespace B2B.Controllers
{
    public class CommonFunctionsController : BaseController
    {
        public string FirmaAdiVer(int FirmaId)
        {
            var DonenDeger = ctx.Firmalar.FirstOrDefault(q => q.Id == FirmaId);
            if(DonenDeger!=null)
            {
                return DonenDeger.FirmaAdi;
            }
            else
            {
                return "Firma Yok/Silinmiş";
            }
        }
        public string KullanicininAdiSoyadi(int UserId)
        {
            var DonenDeger = ctx.Kullanicilar.FirstOrDefault(q => q.Id == UserId);
            if (DonenDeger != null)
            {
                return DonenDeger.Adi;
            }
            else
            {
                return "Kullanıcı Yok/Silinmiş";
            }
        }

        public string UrunKategoriNameVer(int id)
        {
            var DonenDeger = ctx.Kategoriler.FirstOrDefault(q => q.Id == id);
            if(DonenDeger!=null)
            {
                return DonenDeger.KategoriBaslik;
            }
            else
            {
                return "Kategori Yok/Kaldırılmış";
            }
            
        }
        public decimal FirmayaAitTumSiparislerinToplamTutari(int FirmaId)
        {
            return ctx.Siparisler.Where(q => q.FirmaId == FirmaId).Sum(q => q.SiparisToplami).GetValueOrDefault(0);
        }
        public string SiparisDurumuVer(int SiparisDurumu)
        {
            string Durum = SiparisDurumu == 1 ? "Tamamlandı"
                : SiparisDurumu == 2 ? "Onaylandı Kargo Bekliyor"
                : SiparisDurumu == 3 ? "Gönderildi"
                : SiparisDurumu == 4 ? "Ödeme bekliyor"
                : SiparisDurumu == 0 ? "Onay Bekleniyor"
                : "İletişime geçiniz";
            return Durum;
        }
        public string GirdiDurumVer(int DurumId)
        {
            string Durum = DurumId == 1 ? "Tamamlandı"
                : DurumId == 2 ? "Onaylandı, Kargo Bekliyor"
                : DurumId == 3 ? "Gönderildi"
                : DurumId == 4 ? "Ödeme Bekliyor"
                : DurumId == 0 ? "Onay Bekleniyor"
                : "İletişime Geçiniz";
            return Durum;
        }
        public string LabelVer(string DurumId)
        {
            string Durum = DurumId == "Onay Bekleniyor" ? " label-warning"
                : DurumId == "Tamamlandı" ? " label-success"
                : DurumId == "Onaylandı Kargo Bekliyor" ? " label-warning"
                : DurumId == "Gönderildi" ? " label-warning"
                : " label-danger";
            return Durum;
        }
        public void Log(Aktivite Aktivite)
        {
            Kernel.MakeLog(Aktivite);
        }
        public JsonResult GonderimTipleri()
        {
            UserHolder UserInfo = getAktifKullanici();

            List<GONDERI_TIPLERI> Gonderiler = UserInfo.KullaniciYetkisi == "su" ? ctx.GonderiTipleri.OrderBy(q => q.Id).ToList()
                : ctx.GonderiTipleri.Where(q => q.GonderiType != 0).ToList();

            return Json(Gonderiler, JsonRequestBehavior.AllowGet);
        }
        public string EchoCurrent(decimal Amount)
        {
            return string.Format("{0:C}", Amount);
        }


    }
    public class CommonFunctionsForAdminController : BaseController
    {
        [AuthorizeUser(Roles = ("su"))]
        public decimal FirmaBakiyeVer(int FirmaId)
        {
            return ctx.Muhasebe.Where(q => q.FirmaId == FirmaId).FirstOrDefault().Bakiye;
        }
    }

}

b2b/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using B2B.Models.Entity;
using B2B.Dto;

namespace B2B.Controllers
{
    public partial class ProductsController : BaseController
    {
        CommonFunctionsController OrtakFonksiyonlar = new CommonFunctionsController();
        //
        // GET: /Products/

        public ActionResult ProductList()
        {
            var k = (from item in ctx.Kategoriler.Where(q => q.KategoriGoster == 1 && q.KategoriUst == 0).OrderBy(q => q.KategoriSira).ToList()
                     select new UrunlerDto.KategoriListele()
                     {
                         ID = item.Id,
                         KategoriBaslik = item.KategoriBaslik,
                         KategoriGoster = item.KategoriGoster,
                         KategoriSira = item.KategoriSira,
                         UstKategorisi = item.KategoriUst,
                         AltKategorileri = (from x in ctx.Kategoriler.Where(q => q.KategoriUst == item.Id).OrderBy(q => q.KategoriSira).ToList()
                                            select new UrunlerDto.KategoriListeleAlt()
                                            {
                                                ID = x.Id,
                                                KategoriBaslik = x.KategoriBaslik,
                                                KategoriGoster = x.KategoriGoster,
                                                KategoriSira = x.KategoriSira,
                                                UstKategorisi = x.KategoriUst
                                            }).ToList()
                     }).ToList();
            ViewBag.FavoriUrunler = FavoriUrunleriListele_ClassTaban(3);
            if (k != null)
            {
                ViewBag.KategoriBaslik = k[0].KategoriBaslik;
            }
            return View(k);
        }
        public string KategoriAdiVer(int KategoriId)
        {
            return ctx.Kategoriler.FirstOrDefault(q => q.Id == KategoriId).KategoriBaslik;
        }
        public PartialViewResult ProductDetails(int id)
        {
            PRODUCTS p = ctx.Urunler.FirstOrDefault(q => q.Id == id);
            p.UrunAciklama = Kernel.DecodeHTML(p.UrunAciklama);
            ViewBag.UrunKategoriName = OrtakFonksiyonlar.UrunKategoriNameVer(p.UrunKategorisi);
            // Aktivite _a = new Aktivite(); _a.AktiviteSTR = p.UrunAdi + " ürününü inceliyor"; _a.AktiviteTarihSaat = DateTime.Now; _a.AktiviteTipi = 3; _a.FirmaId = getAktifKullanici().FirmaId; _a.UserId = getAktifKullanici().UserId;
            var SunlaraGozatin = (from item in Kategori_Icinde_UrunBul(p.UrunKategorisi).ToList()
                                  select new UrunlerDto.BenzeyenUrunListesi()
                                  {
                                      AsilUrunId = item.UrunId,
                                      BenzeyenUrunBasligi = item.UrunAdi,
                                      BenzeyenUrunFiyati = item.UrunFiyat,
                                      BenzeyenUrunFotografi = item.UrunFoto,
                                      BenzeyenUrunId = item.UrunId
                                  }).ToList();
            ViewBag.SunlaraGozat = SunlaraGozatin;
            ViewBag.Desc = p.UrunAciklama;
            ViewBag.ogTitle = p.UrunAdi;
            ViewBag.ogImg = "https://cicekgider.com/Upload/imajlar/" + p.UrunFotografi;

            return PartialView(p);
        }
        public string UrunOzellikVer(int? OzellikId)
        {
            return ctx.UrunOzellikleri.Where(q => q.Id == OzellikId).Select(q => q.Ozellik).FirstOrDefault();
        }
        public string UrunAdiVer(int UrunId) // Ürün Adı Ver
        {
            var donendeger = ctx.Urunler.FirstOrDefault(q => q.Id == UrunId);
            if (donendeger != null)
            {
                return donendeger.UrunAdi;
            }
            else
            {
                return "ÜRÜN SİSTEMDEN KALDIRILMIŞ";
            }
        }
        public string UrunKategoriVer(int UstKategoriId)
        {
            return ctx.Kategoriler.Where(q => q.Id == UstKategoriId).Select(q => q.KategoriBaslik).FirstOrDefault();
        }
        public string UrunAgirlikSorgula(int AgirlikId)
        {
            return ctx.UrunlerAgirlikOlculeri.Where(q => q.Id == AgirlikId).Select(q => q.WeightShortCut).FirstOrDefault();
        }
        public string OdemeSekliVer(int odemeSekilId)
        {
            string p = ctx.OdemeSekilleri.Where(q => q.Id == odemeSekilId).Select(q => q.OdemeAdi).FirstOrDefault();
            return p;
        }
        public string FotografVer(int id)
        {
            var donendeger = ctx.Urunler.FirstOrDefault(q => q.Id == id);
            if (donendeger != null)
            {
                return donendeger.UrunFotografi;
            }
            else
            {
                return "ÜRÜN SİSTEMDEN KALDIRILMIŞ";
            }
        }
        public string MarkaVer(int urunId)
        {
            int j = ctx.Urunler.FirstOrDefault(q => q.Id == urunId).MarkaId;
            return ctx.Markalar.FirstOrDefault(q => q.Id == j).Marka;
        }
        public string FiyatVer(int urunId)
        {
            var donendeger = ctx.Urunler.FirstOrDefault(q => q.Id == urunId);
            if (donendeger != null)
            {
                return donendeger.UrunFiyat.ToString();
            }
            else
            {
                return "ÜRÜN SİSTEMDEN KALDIRILMIŞ";
            }
        }
        public string UrunKoduVer(int urunId)
        {
            var donendeger = ctx.Urunler.FirstOrDefault(q => q.Id == urunId);
            if (donendeger != null)
            {
                return donendeger.UrunKodu;
            }
            else
            {
                return "ÜRÜN SİSTEMDEN KALDIRILMIŞ";
            }
        }
        public decimal UrunFiyatVer(int UrunId)
        {
            return ctx.Urunler.Where(q => q.Id == UrunId).FirstOrDefault().UrunFiyat;
        }
        public bool MinSipKontrol(int UrunId, decimal eklenmenIstenenAdet)
        {
            decimal urununMinSipi = ctx.Urunler.Where(q => q.Id == UrunId).FirstOrDefault().MinimumSiparisAdeti;
            if (eklenmenIstenenAdet < urununMinSipi)
            {
                return false;
            }
            else
            {
                return true;
            }
        }
        public decimal StokVer(int urunId)
        {
            decimal deger = 0;
            var urun = ctx.Urunler.SingleOrDefault(q => q.Id == urunId);
            try
            {
                deger = urun.Stok;
            }
            catch (Exception e)
            {
                throw new ArgumentException(e.Message);
            }
            return deger;
        }

        public string UrunFotografiVer(int id)
        {
            string donendeger;
            var urun = ctx.Urunler.SingleOrDefault(q => q.Id == id);
            try
            {
                if (System.IO.File.Exists(Server.MapPath("~/Upload/imajlar/" + urun.UrunFotografi)))
                {
                    if (urun.UrunFotografi != "" || urun.UrunFotografi != null)
                        donendeger = urun.UrunFotografi;
                    else
                    {
                        donendeger = "keinFoto.png";
                    }
                }
                else
                {
                    donendeger = "keinFoto.png";
                }
            }
            catch (Exception)
            {
                donendeger = "keinFoto.png";
            }
            return donendeger;
        }

        public decimal IndirimliUrunuHesapla(int indirimId, decimal urunFiyat)
        {
            int indirimOrani = ctx.UrunlerIndirim.Where(q => q.Id == indirimId).FirstOrDefault().IndirimOrani;
            decimal temp = 100 - indirimOrani;
            decimal temp2 = temp / 100;
            return temp2 * urunFiyat;
        }
        public ICollection<PAYMENT_TYPES> OdemeSekliListesiDonustur(ICollection<PRODUCTS_PAYMENT_TYPES> o)
        {
            List<PAYMENT_TYPES> p = new List<PAYMENT_TYPES>();
            foreach (PRODUCTS_PAYMENT_TYPES item in o)
            {
                p.Add(new PAYMENT_TYPES()
                {
                    Id = item.Id,
                    OdemeAdi = OdemeSekliVer(int.Parse(item.OdemeSekli))
                });
            }
            return p;
        }
        public GonderimDetaylari TeslimDetaylariVer(int TeslimDetaylari)
        {
            PRODUCTS_DELIVERY_DETAILS p = ctx.TeslimatDetaylari.Where(q => q.Id == TeslimDetaylari).FirstOrDefault();
            GonderimDetaylari g = new GonderimDetaylari()
            {
                GonderimSuresi = p.TeslimatSuresi,
                GonderimUcreti = p.TeslimatUcreti,
                GonderimTipi = p.TeslimatTuru,
                Montaj = p.MontajTuru
            };
            return g;
        }
        public JsonResult ProductsSimilar(int id)
        {
            var BenzeyenUrunListesi = (from item in ctx.UrunlerBenzer.Where(q => q.UrunId == id).ToList()
                                       select new UrunlerDto.BenzeyenUrunListesi()
                                       {
                                           AsilUrunId = item.UrunId,
                                           BenzeyenUrunBasligi = UrunAdiVer(item.UrunId),
                                           BenzeyenUrunFiyati = UrunFiyatVer(item.UrunId),
                                           BenzeyenUrunFotografi = UrunFotografiVer(item.UrunId),
                                           BenzeyenUrunId = item.BenzeyenUrunId
                                       }).ToList();
            return Json(BenzeyenUrunListesi, JsonRequestBehavior.AllowGet);
        }
        public JsonResult FavoriUrunleriListele(int Adet) // varsayılan adet 1
        {

b2b/Views/Siparis/Basarili.cshtml
@{
    ViewBag.Title = "Sipariş Onayı";
    Layout = "~/Views/_NewMaster.cshtml";
}
<!-- main-container -->
  <div class="main-container col2-right-layout">
    <div class="main container">
      <div class="row">
        <section class="col-sm-9 wow bounceInUp animated">
        <div class="col-main">
          <div class="page-title">
            <h2>Sipariş Onaylandı</h2>
          </div>
          <div class="static-contain">
            <p><img src=/assets/images/check.svg /> Siparişiniz Onaylandı</p>
              <h2>Şimdi ne yapacağım?</h2>
            <p>Siparişiniz onaylandı. Belirtilen süre içerisinde çiçeğiniz belirttiğiniz adrese ulaşır.
                <br /> 444 2 151 numaralı telefondan siparişinizin durumunu kontrol edebilirsiniz.</p>
            </div></div>
        </section>
        <aside class="col-right sidebar col-sm-3 wow bounceInUp animated">
          <div class="block block-company">
            <div class="block-title">Gider Çiçek </div>
            <div class="block-content">
              <ol id="recently-viewed-items">
                <li class="item odd"><strong>Ana sayfa</strong></li>
              </ol>
            </div>
          </div>
        </aside>
      </div>
    </div>
  </div>
  <!--End main-container --> 

b2b/Views/Siparis/GecmisSiparisleriListele.cshtml
@{
    ViewBag.Title = "GecmisSiparisleriListele";
    Layout = "~/Views/_Master.cshtml";
}
@model List<B2B.Dto.GecmisSiparisAyrintilari>

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">Ana Sayfa</h4>
        <ol class="breadcrumb">
            <li>
                Siparişler
            </li>
            <li class="active">
                Geçmiş Siparişleri Listele
            </li>
        </ol>
    </div>
</div>
<!-- Page-Title -->
<div class="row">
    <div class="col-lg-12">
        <div class="card-box">

            <div class="table-responsive">
                <table class="table table-actions-bar table-striped table-bordered dataTable">
                    <thead>
                        <tr>
                            <th>Ürün</th>
                            <th>Tarih</th>
                            <th>Sipariş Kodu</th>
                            <th>Durum</th>
                            <th>Tutar</th>
                            <th style="min-width: 80px;">İşlem</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <img src="/Upload/imajlar/@Html.Action("UrunFotografiVer", "Products", new { id = item.SiparisUrunleri.FirstOrDefault().UrunId })" class="img-responsive" style="height:25px">
                                </td>
                                <td>@item.SiparisTarihi</td>
                                <td><a href="/Siparis/SiparisIncele/@item.Id">@item.SiparisKodu</a></td>
                                <td>
                                    <span class="label @{ Html.RenderAction("LabelVer", "CommonFunctions", new { DurumId = item.SiparisDurum }); }">@item.SiparisDurum</span>
                                </td>
                                <td>@string.Format("{0:C}", item.SiparisToplami)</td>
                                <td>
                                    <a href="/Siparis/SiparisIncele/@item.Id" class="table-action-btn"><i class="md md-find-in-page"></i></a>
                                    <a href="#" onclick="javascript:SiparisiTekrarla(@item.Id);" class="table-action-btn"><i class="md md-add-shopping-cart"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

    </div>
    <!-- end col -->


</div>
<script>
    function SiparisiTekrarla(siparisNo) {
        $.get('@Url.Content("~/")Sepet/SiparisiTekrarla', {
            'siparisNo' : siparisNo
        }, function (d) {
            swal("Başarılı", "Sipariş tekrar sepetinize eklendi", "success");
        });
    }
</script>
<!-- Sweet-Alert  -->
<script src="/assets/plugins/sweetalert/dist/sweetalert.min.js"></script>
<script src="/assets/pages/jquery.sweet-alert.init.js"></script>

<!-- Sweet-Alert  -->
<script src="/assets/plugins/sweetalert/dist/sweetalert.min.js"></script>
<script src="/assets/pages/jquery.sweet-alert.init.js"></script>
<!-- Datatable js -->
<script src="/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/assets/plugins/datatables/dataTables.bootstrap.js"></script>
<script src="/assets/plugins/datatables/dataTables.keyTable.min.js"></script>
<script src="/assets/plugins/datatables/dataTables.buttons.min.js"></script>
<script src="/assets/plugins/datatables/buttons.bootstrap.min.js"></script>
<script src="/assets/plugins/datatables/jszip.min.js"></script>
<script src="/assets/plugins/datatables/pdfmake.min.js"></script>
<script src="/assets/plugins/datatables/vfs_fonts.js"></script>
<script src="/assets/plugins/datatables/buttons.html5.min.js"></script>
<script src="/assets/plugins/datatables/buttons.print.min.js"></script>
<!-- Data table init -->
<script src="/assets/pages/datatables.init.js"></script>
<!-- Modal-Effect (Custom box)-->
<script src="/assets/plugins/custombox/dist/custombox.min.js"></script>
<script src="/assets/plugins/custombox/dist/legacy.min.js"></script>

<script type="text/javascript">
    TableManageButtons.init();
</script>

b2b/Views/Siparis/MarkayaGoreSiparis.cshtml
@{
    ViewBag.Title = "MarkalariListele";
    Layout = "~/Views/_Master.cshtml";
}
@model B2B.Dto.MarkayaGoreAramaSinifi
<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">

        <h4 class="page-title">Detaylı arama</h4>
        <ol class="breadcrumb">
            <li>
                <a href="#">Ana Sayfa</a>
            </li>
            <li>
                Sipariş
            </li>
            <li class="active">Detaylı arama</li>
        </ol>

    </div>
</div>
<!-- Page-Title -->

<div class="row">
    <div class="col-sm-8">

        <div class="portfolioContainer m-b-15">
            <!--#deneme yapacağız-->
            @{
                var _x = Model.Urunler;
                if (Request.QueryString["MarkaId"] == null)
                {
                    _x = Model.Urunler;
                }
                else
                {
                    _x = Model.Urunler.Where(q => q.Id == int.Parse(Request.QueryString["MarkaId"])).ToList();
                }
            }
            @foreach (var item in _x)
            {
                <div class="col-sm-6 col-lg-3 col-md-4">
                    <div class="product-list-box thumb">
                        <a href="/Products/ProductDetails/@item.Id">
                            <img src="/Upload/imajlar/@Html.Action("UrunFotografiVer", "Products", new { id = item.Id })" class="thumb-img" style="width:120px" alt="work-thumbnail">
                        </a>
                        <div class="detail">
                            <h4 class="m-t-0 m-b-5"><a href="/Products/ProductDetails/@item.Id" class="text-dark">@Html.Action("UrunAdiVer", "Products", new { UrunId = item.Id })</a></h4>
                            <div class="rating">
                                <ul class="list-inline">
                                    <li><a class="fa fa-star" href=""></a></li>
                                    <li><a class="fa fa-star" href=""></a></li>
                                    <li><a class="fa fa-star" href=""></a></li>
                                    <li><a class="fa fa-star" href=""></a></li>
                                    <li><a class="fa fa-star" href=""></a></li>
                                </ul>
                            </div>
                            <h5 class="m-0"><span class="text-custom paraFormatla">@string.Format("{0:C}", Html.Action("FiyatVer", "Products", new { urunId = item.Id }))</span></h5>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>

    <div class="col-md-4">
        <div class="portlet">
            <div class="portlet-heading bg-danger">
                <h3 class="portlet-title">
                    Markalar Listeleniyor
                </h3>
                <div class="portlet-widgets">
                    <a href="javascript:;" data-toggle="reload"><i class="ion-refresh"></i></a>
                    <span class="divider"></span>
                    <a data-toggle="collapse" data-parent="#accordion1" href="#bg-danger"><i class="ion-minus-round"></i></a>
                    <span class="divider"></span>
                    <a href="#" data-toggle="remove"><i class="ion-close-round"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="bg-danger" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <div id="basicTree">
                        @foreach (var item in Model.Markalar.OrderBy(q => q.Marka).Where(q => q.MarkaAltId == 0))
                        {
                            <ul data-listingId="@item.Id">
                                <li data-jstree='{"opened":true}'>
                                    <a href="?MarkaId=@item.Id">@item.Marka</a>
                                    @{
                                        if (Model.Markalar.SingleOrDefault(q => q.MarkaAltId == item.Id) != null)
                                        {
                                            <ul><li><a href="?MarkaId=@item.Id">@Model.Markalar.FirstOrDefault(q => q.MarkaAltId == item.Id).Marka</a></li></ul>
                                        }
                                    }
                                </li>
                            </ul>
                                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- ladda button  -->
<script src="/assets/plugins/ladda-buttons/js/spin.min.js"></script>
<script src="/assets/plugins/ladda-buttons/js/ladda.min.js"></script>
<script src="/assets/plugins/ladda-buttons/js/ladda.jquery.min.js"></script>
<!-- Tree view js -->
<script src="/assets/plugins/jstree/jstree.min.js"></script>
<script>
    $(document).ready(function () {

        // Bind normal buttons
        $('.ladda-button').ladda('bind', { timeout: 2000 });

        // Bind progress buttons and simulate loading progress
        Ladda.bind('.progress-demo .ladda-button', {
            callback: function (instance) {
                var progress = 0;
                var interval = setInterval(function () {
                    progress = Math.min(progress + Math.random() * 0.1, 1);
                    instance.setProgress(progress);

                    if (progress === 1) {
                        instance.stop();
                        clearInterval(interval);
                    }
                }, 200);
            }
        });


        var l = $('.ladda-button-demo').ladda();

        l.click(function () {
            // Start loading
            l.ladda('start');

            // Timeout example
            // Do something in backend and then stop ladda
            setTimeout(function () {
                l.ladda('stop');
            }, 12000)
        });

    });

    //basic trw
    $('#basicTree').jstree({
        'core': {
            'themes': {
                'responsive': false
            }
        },
        'types': {
            'default': {
                'icon': 'md md-keyboard-arrow-right'
            },
            'file': {
                'icon': 'md md-insert-drive-file'
            }
        },
        'plugins': ['types']
    });
    

</script>

b2b/Views/Siparis/Problem.cshtml
@{
    ViewBag.Title = "Sipariş Onayı";
    Layout = "~/Views/_NewMaster.cshtml";
}
<!-- main-container -->
  <div class="main-container col2-right-layout">
    <div class="main container">
      <div class="row">
        <section class="col-sm-9 wow bounceInUp animated">
        <div class="col-main">
          <div class="page-title">
            <h2>Hata Oluştu</h2>
          </div>
          <div class="static-contain">
            <p><img src="/assets/images/fail.png" height="90" /> Siparişinizin tutarını kredi kartınızdan çekemedik.<br /><span style="color:#ff0000">Bankadan gelen hata mesajı : @Request.QueryString["m"] </span>
               <br /> Lütfen <a href="/Sepet/Index">burayı tıklayarak</a> tekrar deneyiniz.
            </p>
            </div></div>
        </section>
        <aside class="col-right sidebar col-sm-3 wow bounceInUp animated">
          <div class="block block-company">
            <div class="block-title">Gider Çiçek </div>
            <div class="block-content">
              <ol id="recently-viewed-items">
                <li class="item odd"><strong>Ana sayfa</strong></li>
              </ol>
            </div>
          </div>
        </aside>
      </div>
    </div>
  </div>
  <!--End main-container --> 